# frozen_string_literal: true

require "yaml"

module ArbitraryDefinitions
  # Reads the YAML under `_data/tokens/` and compiles it into one stylesheet
  # of CSS custom properties.
  #
  # The YAML is the source of truth. Nothing else in the repository is allowed
  # to write a raw hex, a raw pixel value, or a raw duration — the SCSS reads
  # `var(--ad-*)` and the docs read the same YAML through Liquid, so the
  # swatch on the page and the colour in the button are the same fact rendered
  # twice.
  class TokenSet
    class UnknownReference < StandardError; end

    # A `ramp.step` reference, e.g. `persimmon.600`.
    REFERENCE = /\A([a-z][a-z0-9_]*)\.([a-z0-9]+)\z/

    attr_reader :prefix, :ramps, :semantic, :scale, :contrast

    def initialize(dir:, prefix: "ad")
      @prefix   = prefix
      @ramps    = load_yaml(File.join(dir, "color.yml")).fetch("ramps")
      @semantic = load_yaml(File.join(dir, "semantic.yml")).fetch("groups")
      @scale    = load_yaml(File.join(dir, "scale.yml"))
      @contrast = load_yaml(File.join(dir, "contrast.yml"))
      @index    = build_ramp_index
    end

    # The contrast contract, flattened into one list of
    # {foreground, background, minimum, …} rows. The test suite asserts these
    # and the Colour page renders them, so neither can quietly fall behind the
    # other.
    def contrast_pairs
      contrast.flat_map do |_key, section|
        section.fetch("pairs").map do |pair|
          pair.merge(
            "kind"     => section.fetch("label"),
            "minimum"  => section.fetch("minimum"),
            "standard" => section.fetch("standard"),
          )
        end
      end
    end

    # "ink.900" -> "#26231f"; a literal colour passes straight through.
    def resolve(value)
      value = value.to_s
      match = REFERENCE.match(value)
      return value unless match

      @index.fetch(value) do
        raise UnknownReference, "no token #{value.inspect} in ramp #{match[1].inspect}"
      end
    end

    # Every semantic token, flattened, with both themes resolved. The docs use
    # this to render the alias tables.
    def semantic_tokens
      semantic.flat_map do |group|
        group.fetch("tokens").map do |token|
          {
            "group" => group.fetch("name"),
            "token" => token.fetch("token"),
            "name"  => custom_property(token.fetch("token")),
            "light" => resolve(token.fetch("light")),
            "dark"  => resolve(token.fetch("dark")),
            "light_ref" => token.fetch("light"),
            "dark_ref"  => token.fetch("dark"),
            "usage" => token["usage"],
          }
        end
      end
    end

    def custom_property(name)
      "--#{prefix}-#{name}"
    end

    def to_css
      [
        header,
        root_block,
        dark_block,
        forced_dark_block,
        reduced_motion_block,
      ].join("\n\n") << "\n"
    end

    private

    def load_yaml(path)
      YAML.safe_load_file(path, aliases: true)
    end

    def build_ramp_index
      ramps.each_with_object({}) do |ramp, index|
        ramp.fetch("steps").each do |step|
          index["#{ramp.fetch('name')}.#{step.fetch('step')}"] = step.fetch("value")
        end
      end
    end

    def header
      <<~CSS.strip
        /* Generated by _plugins/token_generator.rb from _data/tokens/*.yml.
           Do not edit by hand — edit the YAML and rebuild. */
      CSS
    end

    def root_block
      lines = []
      lines << "  /* Palette ramps — reference only. Components use the aliases below. */"
      ramps.each do |ramp|
        ramp.fetch("steps").each do |step|
          lines << declaration("#{ramp.fetch('name')}-#{step.fetch('step')}", step.fetch("value"))
        end
      end

      semantic.each do |group|
        lines << ""
        lines << "  /* #{group.fetch('name')} */"
        group.fetch("tokens").each do |token|
          lines << declaration(token.fetch("token"), resolve(token.fetch("light")))
        end
      end

      scale_groups.each do |label, entries|
        lines << ""
        lines << "  /* #{label} */"
        entries.each { |entry| lines << declaration(entry.fetch("token"), entry.fetch("value")) }
      end

      wrap(":root", lines)
    end

    def dark_block
      lines = ['  color-scheme: dark;']
      semantic.each do |group|
        lines << ""
        lines << "  /* #{group.fetch('name')} */"
        group.fetch("tokens").each do |token|
          lines << declaration(token.fetch("token"), resolve(token.fetch("dark")))
        end
      end

      body = wrap("  :root:not([data-theme=\"light\"])", lines, indent: "  ")
      <<~CSS.rstrip
        @media (prefers-color-scheme: dark) {
        #{body}
        }
      CSS
    end

    # An explicit choice from the theme toggle has to beat the media query in
    # both directions, so the dark declarations are emitted a second time
    # under the attribute selector.
    def forced_dark_block
      lines = ['  color-scheme: dark;']
      semantic.each do |group|
        group.fetch("tokens").each do |token|
          lines << declaration(token.fetch("token"), resolve(token.fetch("dark")))
        end
      end

      wrap(':root[data-theme="dark"]', lines)
    end

    def reduced_motion_block
      durations = scale.dig("motion", "durations") || []
      lines = durations.map { |entry| declaration(entry.fetch("token"), "0ms") }

      <<~CSS.rstrip
        @media (prefers-reduced-motion: reduce) {
        #{wrap('  :root', lines, indent: '  ')}
        }
      CSS
    end

    # The non-colour token groups, in the order they should appear, paired
    # with a human label for the comment banner.
    def scale_groups
      groups = []
      typography = scale.fetch("typography")
      groups << ["Type families", typography.fetch("families")]
      groups << ["Type sizes", typography.fetch("sizes")]
      groups << ["Line heights", typography.fetch("line_heights")]
      groups << ["Weights", typography.fetch("weights")]
      groups << ["Tracking", typography.fetch("tracking")]
      groups << ["Space", scale.dig("space", "scale")]
      groups << ["Radius", scale.dig("radius", "scale")]
      groups << ["Elevation", scale.dig("elevation", "scale")]
      groups << ["Durations", scale.dig("motion", "durations")]
      groups << ["Easings", scale.dig("motion", "easings")]
      groups << ["Layout", scale.dig("layout", "scale")]
      groups.reject { |(_, entries)| entries.nil? || entries.empty? }
    end

    def declaration(name, value)
      "  #{custom_property(name)}: #{value};"
    end

    def wrap(selector, lines, indent: "")
      body = lines.map { |line| line.empty? ? "" : "#{indent}#{line}" }.join("\n")
      "#{selector} {\n#{body}\n#{indent}}"
    end
  end
end
